# Generated by Django 4.2.1 on 2023-10-15 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepicture',
            name='avatar',
            field=models.FileField(blank=True, upload_to='avatars'),
        ),
    ]
