# Generated by Django 4.2.1 on 2023-10-22 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reaction',
            name='timeline_items',
        ),
    ]
